optimize

diff --git a/bin/ipkg b/bin/ipkg
--- a/bin/ipkg
+++ b/bin/ipkg
@@ -1,5 +1,11 @@
 #!/bin/sh
 
+#------------------------------------------------------------------------------
+# https://clang.llvm.org/docs/ClangCommandLineReference.html
+# https://clang.llvm.org/docs/CrossCompilation.html
+# https://commandlinefanatic.com/cgi-bin/showarticle.cgi?article=art024
+#------------------------------------------------------------------------------
+
 # MY represents this software's
 MY_VERSION=0.1.0
 MY_HOME_PAGE='https://github.com/leleliu008/ipkg'
@@ -590,8 +596,6 @@ install_packages() {
 install_a_package() {
     fetch_a_package "$1"
     
-    is_sha256sum_match "$FETCH_OUTPUT_FILE_PATH" "$sha256" || die_from_sha256sum_mismatch 
-    
     if DIR_SRC=$(mktemp -d) ; then
         cd "$DIR_SRC" || exit 1
     else
@@ -686,32 +690,47 @@ info_packages() {
 
 info_a_package() {
     load_formula_of_a_package "$1"
-    
-    echo "name      : $1"
+
+    echo "name      : $(mark_is_package_installed_or_not $1)"
+
+    case $url in
+        *.git);;
+        *)  echo "version   : $version"
+    esac
+
     echo "summary   : $summary"
     echo "homepage  : $homepage"
-    echo "available : $version"
-    
+
     [ -z "$dependencies" ] || {
-        msg "depend_on :"
         unset DEPENDENCIES
+
         for dependencyPkgName in $dependencies
         do
             if [ -z "$DEPENDENCIES" ] ; then
-                DEPENDENCIES=true
-                msg " "
+                DEPENDENCIES="depend_on : $(mark_is_package_installed_or_not $dependencyPkgName)"
             else
-                msg "            "
-            fi
-
-            if is_package_installed "$dependencyPkgName" ; then
-                echo "$dependencyPkgName ${COLOR_GREEN}✔${COLOR_OFF}"
-            else
-                echo "$dependencyPkgName ${COLOR_RED}✘${COLOR_OFF}"
+                DEPENDENCIES="$DEPENDENCIES | $(mark_is_package_installed_or_not $dependencyPkgName)"
             fi
         done
+
+        echo "$DEPENDENCIES"
     }
-     
+
+    echo "src_url   : $url"
+
+    case $url in
+        *.git)
+            FETCH_OUTPUT_FILE_PATH="$DIR_DOWNLOAD/$(basename $url .git)"
+            if [ -d "$FETCH_OUTPUT_FILE_PATH" ] ; then
+                echo "src_cache ${COLOR_PURPLE}==>${COLOR_OFF} $FETCH_OUTPUT_FILE_PATH"
+            fi
+            ;;
+        *)  FETCH_OUTPUT_FILE_PATH="$DIR_DOWNLOAD/$(basename $url)"
+            if [ -f "$FETCH_OUTPUT_FILE_PATH" ] ; then
+                echo "src_cache ${COLOR_PURPLE}==>${COLOR_OFF} $FETCH_OUTPUT_FILE_PATH"
+            fi
+    esac
+
     if is_package_installed "$1" ; then
         for PLATFORM in $(list_support_platforms)
         do
@@ -733,6 +752,14 @@ info_a_package() {
     fi
 }
 
+mark_is_package_installed_or_not() {
+    if is_package_installed "$1" ; then
+        echo "${COLOR_GREEN}$1${COLOR_OFF}"
+    else
+        echo "${COLOR_RED}$1${COLOR_OFF}"
+    fi
+}
+
 load_formula_of_a_package() {
     is_package_available "$1" || die_from_package_is_not_available "$1"
 
@@ -751,10 +778,14 @@ load_formula_of_a_package() {
     
     [ -z "$summary" ]  && die "summary variable must be specified in $FORMULA_FILE_PATH"
     [ -z "$homepage" ] && die "homepage variable must be specified in $FORMULA_FILE_PATH"
-    [ -z "$sha256" ]   && die "sha256 variable must be specified in $FORMULA_FILE_PATH"
     [ -z "$url" ]      && die "url variable must be specified in $FORMULA_FILE_PATH"
-    [ -z "$version" ]  && version="$(basename "$url" | awk '{str = tolower($0); gsub(".tar.xz", "", str); gsub(".tar.gz", "", str); gsub(".tar.bz2", "", str); gsub(".tgz", "", str); gsub(".txz", "", str); gsub(".zip", "", str); print(str)}' | awk -F- '{print $NF}')"
-    [ -z "$version" ]  && die "version can't be parsed in $FORMULA_FILE_PATH"
+    
+    case $url in
+        *.git);;
+        *)  [ -z "$sha256" ]   && die "sha256 variable must be specified in $FORMULA_FILE_PATH"
+            [ -z "$version" ]  && version="$(basename "$url" | awk '{str = tolower($0); gsub(".tar.xz", "", str); gsub(".tar.gz", "", str); gsub(".tar.bz2", "", str); gsub(".tgz", "", str); gsub(".txz", "", str); gsub(".zip", "", str); print(str)}' | awk -F- '{print $NF}')"
+            [ -z "$version" ]  && die "version can't be parsed in $FORMULA_FILE_PATH"
+    esac
 }
 
 load_installed_info_of_a_package() {
@@ -991,18 +1022,26 @@ make_env() {
     TARGET_PLATFORM=$(get_target_platform_by_device "$FOR_SIMULATOR")
     
     if [ 'arm64' = "$TARGET_ARCH" ] ; then
-        TARGET_HOST='arm-ios-darwin'
+        TARGET_HOST='aarch64-apple-ios'
     else
-        TARGET_HOST="${TARGET_ARCH}-ios-darwin"
+        TARGET_HOST="${TARGET_ARCH}-apple-ios"
     fi
-     
+    
     export TOOLCHAIN_DIR="$DEVELOPER_DIR/Toolchains/XcodeDefault.xctoolchain/usr/bin"
     export PATH=$TOOLCHAIN_DIR:$PATH
     export SYSROOT="$DEVELOPER_DIR/Platforms/${TARGET_PLATFORM}.platform/Developer/SDKs/${TARGET_PLATFORM}.sdk"
-     
+    
     DIR_INSTALL_PACKAGE="$DIR_PKG/$1"
     DIR_INSTALL_PREFIX="$DIR_INSTALL_PACKAGE/$TARGET_PLATFORM/$TARGET_ARCH"
-    [ -z "$DIR_SRC" ] || DIR_BUILD="$DIR_SRC/$TIMESTAMP_UNIX/$TARGET_PLATFORM/$TARGET_ARCH"
+
+    if [ -n "$DIR_SRC" ] ; then
+        if [ -d "$DIR_SRC" ] ; then
+            DIR_BUILD="$DIR_SRC/$TIMESTAMP_UNIX/$TARGET_PLATFORM/$TARGET_ARCH"
+            mkdir -p "$DIR_BUILD" || exit 1
+        else
+            exit 1
+        fi
+    fi
     
     info "-------------------------------------------------------"
     info "  TARGET_PACKAGE = $1"
@@ -1049,35 +1088,34 @@ make_env() {
     info "           STRIP = $STRIP"
     
     platformLower="$(printf "$TARGET_PLATFORM" | awk '{print(tolower($0))}')"
-    CFLAGS="-arch $TARGET_ARCH -isysroot $SYSROOT -m${platformLower}-version-min=$TARGET_PLATFORM_MIN_VERSION -Os -pipe -Qunused-arguments"
-
-    [ "$VERBOSE" = 'true' ] && {
-        export CFLAGS="$CFLAGS -v"
-        export PKG_CONFIG_DEBUG_SPEW=set
-    }
     
-    export CFLAGS="$CFLAGS"
-    export CXXFLAGS="$CFLAGS"
-    
+      CFLAGS="-isysroot $SYSROOT -Qunused-arguments -arch $TARGET_ARCH -Os -pipe -m${platformLower}-version-min=$TARGET_PLATFORM_MIN_VERSION"
     CPPFLAGS="-isysroot $SYSROOT -Qunused-arguments"
-    
+     LDFLAGS="-isysroot $SYSROOT -arch $TARGET_ARCH"
+    PKG_CONFIG_PATH=''
+
     case $TARGET_ARCH in
         armv7*)
             CPPFLAGS="$CPPFLAGS -D__arm__"
+            TARGET_CPU_FAMILY='arm'
+            TARGET_CPU_NAME="$TARGET_ARCH"
             ;;
         arm64*)
             CPPFLAGS="$CPPFLAGS -D__arm64__"
+            TARGET_CPU_FAMILY='aarch64'
+            TARGET_CPU_NAME="$TARGET_ARCH"
             ;;
         i386)
             CPPFLAGS="$CPPFLAGS -D__i386__"
+            TARGET_CPU_FAMILY='x86'
+            TARGET_CPU_NAME='i386'
             ;;
         x86_64)
             CPPFLAGS="$CPPFLAGS -D__x86_64__"
+            TARGET_CPU_FAMILY='x86_64'
+            TARGET_CPU_NAME='x86_64'
             ;;
     esac
-    
-    LDFLAGS="-arch $TARGET_ARCH -isysroot $SYSROOT"
-    PKG_CONFIG_PATH=''
     
     for item in $DEPENDENCY_PACKAGE_LIST
     do
@@ -1095,7 +1133,14 @@ make_env() {
         LDFLAGS="-L$ITEM_DIR_LIB $LDFLAGS"
         PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$ITEM_DIR_LIB/pkgconfig"
     done
+
+    [ "$VERBOSE" = 'true' ] && {
+        export CFLAGS="$CFLAGS -v"
+        export PKG_CONFIG_DEBUG_SPEW=set
+    }
     
+    export CFLAGS="$CFLAGS"
+    export CXXFLAGS="$CFLAGS"
     export CPPFLAGS="$CPPFLAGS"
     export LDFLAGS="$LDFLAGS"
     export PKG_CONFIG_PATH="$PKG_CONFIG_PATH"
@@ -1110,16 +1155,19 @@ make_env() {
     info "DIR_INSTALL_PACKAGE = $DIR_INSTALL_PACKAGE"
     info "DIR_INSTALL_PREFIX  = $DIR_INSTALL_PREFIX"
     info "PKG_CONFIG_PATH = $PKG_CONFIG_PATH"
-     
-    [ -z "$DIR_BUILD" ] || {
-        CMAKE_TOOLCHAIN_FILE="$DIR_BUILD/toolchain.cmake"
-        
-        info "CMAKE_TOOLCHAIN_FILE =$CMAKE_TOOLCHAIN_FILE"
-        info "-------------------------------------------------------"
-        
-        mkdir -p "$DIR_BUILD"
 
-        cat > "$CMAKE_TOOLCHAIN_FILE" <<EOF
+    info "-------------------------------------------------------"
+}
+
+# https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling
+# https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_ROOT_PATH.html
+# https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html
+# https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html
+# https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html
+# https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html
+# https://cmake.org/cmake/help/latest/command/enable_testing.html?highlight=build_testing
+cmake() {
+    cat > "$DIR_BUILD/toolchain.cmake" <<EOF
 set(CMAKE_SYSTEM_NAME Darwin)
 set(CMAKE_SYSTEM_PROCESSOR $TARGET_ARCH)
 
@@ -1139,13 +1187,56 @@ set(CMAKE_NM "$NM")
 set(CMAKE_STRIP "$STRIP")
 
 set(CMAKE_OSX_SYSROOT "$SYSROOT")
-
-set(BUILD_SHARED_LIBS OFF)
-set(CMAKE_BUILD_TYPE Release)
-
-set(CMAKE_INSTALL_PREFIX "$DIR_INSTALL_PREFIX")
 EOF
-    }
+    unset -f meson
+
+    command cmake \
+    -DCMAKE_TOOLCHAIN_FILE="$DIR_BUILD/toolchain.cmake" \
+    -DCMAKE_OSX_ARCHITECTURES="$TARGET_ARCH" \
+    -DCMAKE_PREFIX_PATH="$DIR_PKG" \
+    -DCMAKE_FIND_ROOT_PATH="$DIR_PKG" \
+    -DCMAKE_INSTALL_PREFIX="$DIR_INSTALL_PREFIX" \
+    -DCMAKE_BUILD_TYPE=Release \
+    -DBUILD_SHARED_LIBS=OFF \
+    -DBUILD_TESTING=OFF \
+    -G "Unix Makefiles" \
+    -Wno-dev \
+    -S "$DIR_SRC" \
+    -B "$DIR_BUILD" $@ &&
+    make --directory="$DIR_BUILD" install
+}
+
+meson() {
+    unset -f cmake
+
+    CMAKE_EXECUTABLE=$(command -v cmake)
+    
+    PKG_CONFIG_EXECUTABLE=$(command -v pkg-config) ||
+    PKG_CONFIG_EXECUTABLE=$(command -v pkgconf)
+
+    cat >> "$DIR_BUILD/darwin-cross-file" <<EOF
+[host_machine]
+system = 'darwin'
+endian = 'little'
+cpu_family = '$TARGET_CPU_FAMILY'
+cpu = '$TARGET_CPU_NAME'
+
+[binaries]
+c = '$CC'
+cpp = '$CXX'
+ar = '$AR'
+strip = '$STRIP'
+cmake = '$CMAKE_EXECUTABLE'
+pkgconfig = '$PKG_CONFIG_EXECUTABLE'
+EOF
+    command meson setup \
+        --prefix="$DIR_INSTALL_PREFIX" \
+        --buildtype=minsize \
+        --backend=ninja \
+        --cross-file="$DIR_BUILD/darwin-cross-file" \
+        $@ \
+        "$DIR_BUILD" &&
+    ninja -C "$DIR_BUILD" install
 }
 
 create_framework_for_packages() {
