add ccache support

diff --git a/bin/xcpkg b/bin/xcpkg
--- a/bin/xcpkg
+++ b/bin/xcpkg
@@ -776,11 +776,11 @@ __upgrade_self() {
     fi
 
     echo "$COLOR_PURPLE==>$COLOR_OFF ${COLOR_GREEN}mktemp -d$COLOR_OFF"
-    WORK_DIR=$(mktemp -d)
+    WORKING_DIR=$(mktemp -d)
 
-    run cd $WORK_DIR
+    run cd $WORKING_DIR
 
-    fetch "$UPGRADE_SELF_URL" --output-path="$WORK_DIR/self"
+    fetch "$UPGRADE_SELF_URL" --output-path="$WORKING_DIR/self"
 
     __upgrade_self_exit() {
         if [ -w "$CURRENT_SCRIPT_REALPATH" ] ; then
@@ -789,7 +789,7 @@ __upgrade_self() {
             run sudo install -m 755 self "$CURRENT_SCRIPT_REALPATH"
         fi
 
-        run rm -rf $WORK_DIR
+        run rm -rf $WORKING_DIR
     }
 
     trap __upgrade_self_exit EXIT
@@ -860,11 +860,11 @@ __integrate_zsh_completions() {
     fi
 
     echo "$COLOR_PURPLE==>$COLOR_OFF ${COLOR_GREEN}mktemp -d$COLOR_OFF"
-    WORK_DIR=$(mktemp -d)
+    WORKING_DIR=$(mktemp -d)
 
-    run cd $WORK_DIR
+    run cd $WORKING_DIR
 
-    fetch "$ZSH_COMPLETIONS_SCRIPT_URL" --output-path="$WORK_DIR/$ZSH_COMPLETIONS_SCRIPT_FILENAME"
+    fetch "$ZSH_COMPLETIONS_SCRIPT_URL" --output-path="$WORKING_DIR/$ZSH_COMPLETIONS_SCRIPT_FILENAME"
 
     if [ -f "$ZSH_COMPLETIONS_SCRIPT_OUT_FILEPATH" ] ; then
         if [ -w "$ZSH_COMPLETIONS_SCRIPT_OUT_FILEPATH" ] ; then
@@ -884,7 +884,7 @@ __integrate_zsh_completions() {
         fi
     fi
 
-    run rm -rf $WORK_DIR
+    run rm -rf $WORKING_DIR
 
     printf '\n'
     note "${COLOR_YELLOW}you need to run command${COLOR_RED} ${COLOR_GREEN}autoload -U compinit && compinit${COLOR_OFF} ${COLOR_YELLOW}in zsh to make it work.${COLOR_OFF}"
@@ -1261,6 +1261,7 @@ version_of_python_module() {
 # retrive the version of a command from it's name or path
 version_of_command() {
     case $(basename "$1") in
+       ccache) "$1" --version 2> /dev/null | head -n 1 | cut -d ' ' -f3 ;;
         xmake) "$1" --version 2> /dev/null | head -n 1 | cut -d '+' -f1 | cut -d 'v' -f2 ;;
         cmake) "$1" --version 2> /dev/null | head -n 1 | cut -d ' ' -f3 ;;
          rake) "$1" --version 2> /dev/null | head -n 1 | cut -d ' ' -f3 ;;
@@ -3369,7 +3370,7 @@ __load_formula_of_the_given_package() {
 
     unset PACKAGE_LICENSE
 
-    # relative to $WORK_DIR, which contains build script such as configure, Makefile, CMakeLists.txt, meson.build, Cargo.toml, etc.
+    # relative to $WORKING_DIR, which contains build script such as configure, Makefile, CMakeLists.txt, meson.build, Cargo.toml, etc.
     unset PACKAGE_SOURCED
 
     unset PACKAGE_BSYSTEM
@@ -4537,10 +4538,10 @@ __pack_the_given_installed_package() {
 
     step "create work directory"
     echo "$COLOR_PURPLE==>$COLOR_OFF ${COLOR_GREEN}mktemp -d$COLOR_OFF"
-    WORK_DIR=$(mktemp -d)
+    WORKING_DIR=$(mktemp -d)
 
     step "change to work directory"
-    run cd $WORK_DIR
+    run cd $WORKING_DIR
 
     step "make link refer to installed package root dir"
     run ln -s "$MY_INSTALL_DIR/$INSTALLED_PKG_NAME" "$PACKED_DIR_NAME"
@@ -4566,7 +4567,7 @@ __pack_the_given_installed_package() {
     run "du -sh $PACKED_FILE_NAME | cut -f1"
 
     step "delete work directory"
-    run rm -rf $WORK_DIR
+    run rm -rf $WORKING_DIR
 }
 
 get_direct_dependency_package_list_of_the_given_package() {
@@ -4730,7 +4731,7 @@ __install_the_given_package() {
     # beacuse previous package's work direcotory is deleted.
     cd ~ || return 1
 
-    unset WORK_DIR
+    unset WORKING_DIR
     unset SOURCE_DIR
 
     unset TARGET_BUILD_DIR
@@ -4747,16 +4748,16 @@ __install_the_given_package() {
     __install_the_given_package_on_exit() {
         is_package_installed "$INSTALLING_PACKAGE" && return 0
 
-        if [ -z "$WORK_DIR" ] ; then
+        if [ -z "$WORKING_DIR" ] ; then
             die "install $INSTALLING_PACKAGE failed!"
         else
             if [ "$DRYRUN" = yes ] ; then
                 return 0
             fi
             if [ -z "$TARGET_ITEM" ] ; then
-                die "install $INSTALLING_PACKAGE failed! you can go to $WORK_DIR to see see."
+                die "install $INSTALLING_PACKAGE failed! you can go to $WORKING_DIR to see see."
             else
-                die "install $INSTALLING_PACKAGE/$TARGET_ITEM failed! you can go to $WORK_DIR to see see."
+                die "install $INSTALLING_PACKAGE/$TARGET_ITEM failed! you can go to $WORKING_DIR to see see."
             fi
         fi
     }
@@ -4788,6 +4789,10 @@ __install_the_given_package() {
 
     calculate_TARGET_OS_VERS "$PACKAGE_NAME" "$PACKAGE_SDK_API" "$USER_EXPECTED_TARGET_OS_VERS"
 
+    if [ "$CCACHE_ENABLED" = yes ] ; then
+        package add dep.cmd ccache
+    fi
+
     step "handle required dependencies"
     for item in $PACKAGE_DEP_CMD
     do
@@ -4818,12 +4823,14 @@ __install_the_given_package() {
     done
 
     unset PKG_CONFIG
+    unset CCACHE
     unset MESON
     unset CMAKE
     unset GMAKE
     unset NINJA
 
     PKG_CONFIG=$(command -v pkg-config || true)
+    CCACHE=$(command -v ccache || true)
     MESON=$(command -v meson || true)
     CMAKE=$(command -v cmake || true)
     GMAKE=$(command -v gmake || command -v make || true)
@@ -4836,9 +4843,9 @@ __install_the_given_package() {
 
     step "create work directory"
     echo "$COLOR_PURPLE==>$COLOR_OFF ${COLOR_GREEN}mktemp -d$COLOR_OFF"
-    WORK_DIR=$(mktemp -d) || die "create work directory failed."
+    WORKING_DIR=$(mktemp -d) || die "create work directory failed."
 
-    run install -d "$WORK_DIR/$TIMESTAMP_UNIX"
+    run install -d "$WORKING_DIR/$TIMESTAMP_UNIX"
 
     step "calculate dependency packages"
     unset DEPENDENCY_PACKAGE_LIST
@@ -4853,11 +4860,11 @@ __install_the_given_package() {
     fi
 
     step "create common linker script"
-    create_common_linker_script "$WORK_DIR/$TIMESTAMP_UNIX"
+    create_common_linker_script "$WORKING_DIR/$TIMESTAMP_UNIX"
 
     step "create common include.h"
     unset COMMON_INCLUDE_H_FILEPATH
-    COMMON_INCLUDE_H_FILEPATH="$WORK_DIR/$TIMESTAMP_UNIX/include.h"
+    COMMON_INCLUDE_H_FILEPATH="$WORKING_DIR/$TIMESTAMP_UNIX/include.h"
     create_common_include_h "$COMMON_INCLUDE_H_FILEPATH"
     if command -v bat > /dev/null ; then
         run bat --style=plain --paging=never "$COMMON_INCLUDE_H_FILEPATH"
@@ -4878,7 +4885,7 @@ __install_the_given_package() {
                 PACKAGE_GIT_REV=$(cd "$PACKAGE_SRC_PATH" && git rev-parse HEAD || true)
             fi
             if [ -d "$PACKAGE_SRC_PATH" ] ; then
-                run cp -r "$PACKAGE_SRC_PATH/." "$WORK_DIR" || return 1
+                run cp -r "$PACKAGE_SRC_PATH/." "$WORKING_DIR" || return 1
             else
                 die "src.url point to dir is not exist."
             fi
@@ -4887,24 +4894,24 @@ __install_the_given_package() {
             if [ -z "$PACKAGE_GIT_REV" ] ; then
                 PACKAGE_GIT_REV=$(cd "$PACKAGE_SRC_PATH" && git rev-parse HEAD) || return 1
             fi
-            run cp -r "$PACKAGE_SRC_PATH/." "$WORK_DIR" || return 1
+            run cp -r "$PACKAGE_SRC_PATH/." "$WORKING_DIR" || return 1
             ;;
         *.c|*.cc|*.cxx|*.cpp)
-            run cp    "$PACKAGE_SRC_PATH"   "$WORK_DIR" || return 1
+            run cp    "$PACKAGE_SRC_PATH"   "$WORKING_DIR" || return 1
             ;;
         *.zip)
-            run unzip "$PACKAGE_SRC_PATH" -d "$WORK_DIR" || return 1
+            run unzip "$PACKAGE_SRC_PATH" -d "$WORKING_DIR" || return 1
             ;;
         *.tar.xz|*.tar.gz|*.tar.lz|*.tar.bz2|*.tgz|*.txz)
-            run tar xf "$PACKAGE_SRC_PATH" -C "$WORK_DIR" --strip-components 1 || return 1
+            run tar xf "$PACKAGE_SRC_PATH" -C "$WORKING_DIR" --strip-components 1 || return 1
             ;;
         *)  die "unrecognized extension : $PACKAGE_SRC_URL. the supported extensions are .zip .tar.xz .tar.gz .tar.lz .tar.bz2 .tgz .txz"
     esac
 
     if [ -z "$PACKAGE_SOURCED" ] ; then
-        SOURCE_DIR="$WORK_DIR"
+        SOURCE_DIR="$WORKING_DIR"
     else
-        SOURCE_DIR="$WORK_DIR/$PACKAGE_SOURCED"
+        SOURCE_DIR="$WORKING_DIR/$PACKAGE_SOURCED"
     fi
 
     step "change to source directory"
@@ -4915,7 +4922,7 @@ __install_the_given_package() {
 
     step "build for native"
     if command -v build0 > /dev/null ; then
-        NATIVE_BUILD_DIR="$WORK_DIR/$TIMESTAMP_UNIX/native"
+        NATIVE_BUILD_DIR="$WORKING_DIR/$TIMESTAMP_UNIX/native"
         NATIVE_INSTALL_DIR="$MY_HOME_DIR/native/$PACKAGE_NAME"
 
         if [ -f "$NATIVE_INSTALL_DIR/version.txt" ] ; then
@@ -4979,11 +4986,11 @@ __install_the_given_package() {
             echo "
                  BUILD_NJOBS = $BUILD_NJOBS
 
-                    WORK_DIR = $WORK_DIR
+                 WORKING_DIR = $WORKING_DIR
                   SOURCE_DIR = $SOURCE_DIR
             NATIVE_BUILD_DIR = $NATIVE_BUILD_DIR
             NATIVE_INSTALL_DIR = $NATIVE_INSTALL_DIR
-            PWD = $PWD
+                         PWD = $PWD
             "
 
             run build0 || return 1
@@ -5028,7 +5035,7 @@ __install_the_given_package() {
     [ "$DRYRUN" = yes ] && exit
 
     step "record installed abis"
-    run cp "$WORK_DIR/$TIMESTAMP_UNIX/installed-abis" "$MY_INSTALL_DIR/$1/installed-abis"
+    run cp "$WORKING_DIR/$TIMESTAMP_UNIX/installed-abis" "$MY_INSTALL_DIR/$1/installed-abis"
 
     step "record installed metadata"
     __record_installed_metadata_of_the_given_package "$1"
@@ -5036,9 +5043,9 @@ __install_the_given_package() {
     step "record installed files"
     __record_installed_files_of_the_given_package "$1"
 
-    [ "$KEEP_WORK_DIR" = yes ] || {
+    [ "$KEEP_WORKING_DIR" = yes ] || {
         step "clean work directory."
-        run rm -rf "$WORK_DIR"
+        run rm -rf "$WORKING_DIR"
     }
 
     echo
@@ -5074,6 +5081,24 @@ __install_the_given_package_for_the_given_target() {
     if [ "$PACKAGE_BUILD_SYSTEM_CMAKE" = yes ] ; then
         step2 "create cmake toolchain file for ${COLOR_GREEN}$@${COLOR_OFF}"
         __create_cmake_toolchain_file_for_the_given_target $@ || return 1
+    fi
+
+    step2 "create needed directories for ${COLOR_GREEN}$@${COLOR_OFF}"
+    run install -d "$WORKING_DIR/$TARGET_OS_ABI/build"   || return 1
+    run install -d "$WORKING_DIR/$TARGET_OS_ABI/include" || return 1
+    run install -d "$WORKING_DIR/$TARGET_OS_ABI/lib"     || return 1
+    run install -d "$WORKING_DIR/$TARGET_OS_ABI/bin"     || return 1
+
+    step2 "create symbolic link for CC and CXX to use ccache"
+    if [ "$CCACHE_ENABLED" = yes ] ; then
+        if [ -z "$CCACHE" ] ; then
+            die "ccache is not installed."
+        fi
+        run ln -s "$CCACHE" "$WORKING_DIR/$TARGET_OS_ABI/bin/$CC"
+        run ln -s "$CCACHE" "$WORKING_DIR/$TARGET_OS_ABI/bin/$CXX"
+        run export PATH="$WORKING_DIR/$TARGET_OS_ABI/bin:$PATH"
+    else
+        note "ccache is disabled, skipped."
     fi
 
     [ "$DRYRUN" = yes ] && {
@@ -5133,7 +5158,7 @@ __install_the_given_package_for_the_given_target() {
     step2 "install logs for ${COLOR_GREEN}$@${COLOR_OFF}"
     __install_logs_for_the_given_target $@ || return 1
 
-    run "echo '$TARGET_OS_ABI' >> $WORK_DIR/$TIMESTAMP_UNIX/installed-abis"
+    run "echo '$TARGET_OS_ABI' >> $WORKING_DIR/$TIMESTAMP_UNIX/installed-abis"
 }
 
 __justfy_la_files_for_the_given_target() {
@@ -5718,7 +5743,7 @@ __config_variables_for_the_given_target() {
         CXXFLAGS="$CXXFLAGS $PACKAGE_XXFLAGS"
     fi
 
-    TARGET_BUILD_DIR="$WORK_DIR/$TIMESTAMP_UNIX/$TARGET_OS_ABI"
+    TARGET_BUILD_DIR="$WORKING_DIR/$TIMESTAMP_UNIX/$TARGET_OS_ABI"
     TARGET_INSTALL_DIR="$MY_INSTALL_DIR/$PACKAGE_NAME/$TARGET_OS_ABI"
     TARGET_BINARY__DIR="$TARGET_INSTALL_DIR/bin"
     TARGET_INCLUDE_DIR="$TARGET_INSTALL_DIR/include"
@@ -5819,7 +5844,7 @@ __config_variables_for_the_given_target() {
 
         export CARGO_BUILD_JOBS="$BUILD_NJOBS"
 
-        export RUSTFLAGS="-Clink-arg=-L$WORK_DIR/$TIMESTAMP_UNIX"
+        export RUSTFLAGS="-Clink-arg=-L$WORKING_DIR/$TIMESTAMP_UNIX"
 
         # https://libraries.io/cargo/cc
         # https://crates.io/crates/cc
@@ -6014,7 +6039,7 @@ EOF
 
     echo "
     TIMESTAMP_UNIX = $TIMESTAMP_UNIX
-          WORK_DIR = $WORK_DIR
+       WORKING_DIR = $WORKING_DIR
         SOURCE_DIR = $SOURCE_DIR
                PWD = $PWD
 
@@ -6992,6 +7017,8 @@ inspect_install_arguments() {
 
     unset DRYRUN
 
+    CCACHE_ENABLED=yes
+
     LOG_LEVEL_QUIET=0
     LOG_LEVEL_NORMAL=1
     LOG_LEVEL_VERBOSE=2
@@ -7011,7 +7038,7 @@ inspect_install_arguments() {
     INSTALL_DOC=yes
     INSTALL_LIB=yes
 
-    KEEP_WORK_DIR=no
+    KEEP_WORKING_DIR=no
 
     NEED_RUN_TREE=no
     NEED_RUN_PACK=no
@@ -7041,11 +7068,14 @@ inspect_install_arguments() {
             --quiet|-q)
                 LOG_LEVEL=$LOG_LEVEL_QUIET
                 ;;
+            --disable-ccache)
+                CCACHE_ENABLED=no
+                ;;
             --dry-run)
                 DRYRUN=yes
                 ;;
             --keep-work-dir)
-                KEEP_WORK_DIR=yes
+                KEEP_WORKING_DIR=yes
                 ;;
             --tree)
                 NEED_RUN_TREE=yes
