optimized

diff --git a/xcpkg b/xcpkg
--- a/xcpkg
+++ b/xcpkg
@@ -911,12 +911,17 @@ filetype_from_url() {
     unset PACKAGE_XXFLAGS
     unset PACKAGE_LDFLAGS
 
+    unset PACKAGE_ONSTART
     unset PACKAGE_ONREADY
+    unset PACKAGE_ONFINAL
+
     unset PACKAGE_DO12345
     unset PACKAGE_DOPATCH
     unset PACKAGE_PREPARE
     unset PACKAGE_DOBUILD
     unset PACKAGE_DOTWEAK
+
+    unset PACKAGE_CAVEATS
 
     unset PACKAGE_PATCHES
     unset PACKAGE_RESLIST
@@ -988,12 +993,17 @@ filetype_from_url() {
     PACKAGE_PPFLAGS="$(yq '.ppflags | select(. != null)' "$PACKAGE_FORMULA_FILEPATH")"
     PACKAGE_LDFLAGS="$(yq '.ldflags | select(. != null)' "$PACKAGE_FORMULA_FILEPATH")"
 
+    PACKAGE_ONSTART="$(yq '.onstart | select(. != null)' "$PACKAGE_FORMULA_FILEPATH")"
     PACKAGE_ONREADY="$(yq '.onready | select(. != null)' "$PACKAGE_FORMULA_FILEPATH")"
+    PACKAGE_ONFINAL="$(yq '.onfinal | select(. != null)' "$PACKAGE_FORMULA_FILEPATH")"
+
     PACKAGE_DO12345="$(yq '.do12345 | select(. != null)' "$PACKAGE_FORMULA_FILEPATH")"
     PACKAGE_DOPATCH="$(yq '.dopatch | select(. != null)' "$PACKAGE_FORMULA_FILEPATH")"
     PACKAGE_PREPARE="$(yq '.prepare | select(. != null)' "$PACKAGE_FORMULA_FILEPATH")"
     PACKAGE_DOBUILD="$(yq '.install | select(. != null)' "$PACKAGE_FORMULA_FILEPATH")"
     PACKAGE_DOTWEAK="$(yq '.dotweak | select(. != null)' "$PACKAGE_FORMULA_FILEPATH")"
+
+    PACKAGE_CAVEATS="$(yq '.caveats | select(. != null)' "$PACKAGE_FORMULA_FILEPATH")"
 
     PACKAGE_PATCHES="$(yq '.patches | select(. != null)' "$PACKAGE_FORMULA_FILEPATH")"
     PACKAGE_RESLIST="$(yq '.reslist | select(. != null)' "$PACKAGE_FORMULA_FILEPATH")"
@@ -1273,52 +1283,55 @@ filetype_from_url() {
         return 1
     }
 
-    run cp "$PACKAGE_FORMULA_FILEPATH" "$PACKAGE_RECEIPT_FILEPATH"
+    cp "$PACKAGE_FORMULA_FILEPATH" "$PACKAGE_RECEIPT_FILEPATH"
 
-    sed_in_place '/^#src-url: dir:/d' "$PACKAGE_RECEIPT_FILEPATH"
+    sed -i '/^#src-url: dir:/d' "$PACKAGE_RECEIPT_FILEPATH"
 
-    sed_in_place "1i pkgname: $PACKAGE_NAME" "$PACKAGE_RECEIPT_FILEPATH"
+    sed -i "1i pkgname: $PACKAGE_NAME" "$PACKAGE_RECEIPT_FILEPATH"
+
+    grep -q '^pkgtype: ' "$PACKAGE_RECEIPT_FILEPATH" || {
+        sed -i "/^pkgname:/a pkgtype: $PACKAGE_PKGTYPE" "$PACKAGE_RECEIPT_FILEPATH"
+    }
 
     grep -q '^version: ' "$PACKAGE_RECEIPT_FILEPATH" || {
-        sed_in_place "2i version: $PACKAGE_VERSION" "$PACKAGE_RECEIPT_FILEPATH"
+        sed -i "/^pkgtype:/a version: $PACKAGE_VERSION" "$PACKAGE_RECEIPT_FILEPATH"
     }
 
     grep -q '^web-url: ' "$PACKAGE_RECEIPT_FILEPATH" || {
-        sed_in_place "/^git-url:/i web-url: $PACKAGE_GIT_URL" "$PACKAGE_RECEIPT_FILEPATH"
+        sed -i "/^git-url:/i web-url: $PACKAGE_GIT_URL" "$PACKAGE_RECEIPT_FILEPATH"
     }
 
     grep -q '^bsystem: ' "$PACKAGE_RECEIPT_FILEPATH" || {
-        sed_in_place "/^install:/i bsystem: $PACKAGE_BSYSTEM" "$PACKAGE_RECEIPT_FILEPATH"
+        sed -i "/^install:/i bsystem: $PACKAGE_BSYSTEM" "$PACKAGE_RECEIPT_FILEPATH"
     }
 
     grep -q '^binbstd: ' "$PACKAGE_RECEIPT_FILEPATH" || {
-        sed_in_place "/^bsystem:/a binbstd: $PACKAGE_BINBSTD" "$PACKAGE_RECEIPT_FILEPATH"
+        sed -i "/^bsystem:/a binbstd: $PACKAGE_BINBSTD" "$PACKAGE_RECEIPT_FILEPATH"
     }
 
     grep -q '^parallel: ' "$PACKAGE_RECEIPT_FILEPATH" || {
-        sed_in_place "\$a parallel: $PACKAGE_PARALLEL" "$PACKAGE_RECEIPT_FILEPATH"
+        sed -i "\$a parallel: $PACKAGE_PARALLEL" "$PACKAGE_RECEIPT_FILEPATH"
     }
 
     [ -n "$PACKAGE_GIT_SHA" ] && {
         grep -q '^git-sha: ' "$PACKAGE_RECEIPT_FILEPATH" || {
-            sed_in_place "/^git-url:/a git-sha: $PACKAGE_GIT_SHA" "$PACKAGE_RECEIPT_FILEPATH"
+            sed -i "/^git-url:/a git-sha: $PACKAGE_GIT_SHA" "$PACKAGE_RECEIPT_FILEPATH"
         }
 
         grep -q '^git-sha: ' "$PACKAGE_RECEIPT_FILEPATH" || {
-            sed_in_place "3i git-sha: $PACKAGE_GIT_SHA" "$PACKAGE_RECEIPT_FILEPATH"
+            sed -i "3i git-sha: $PACKAGE_GIT_SHA" "$PACKAGE_RECEIPT_FILEPATH"
         }
     }
 
     [ -n "$PACKAGE_DEP_UPP" ] && {
         if grep -q '^dep-upp: ' "$PACKAGE_RECEIPT_FILEPATH" ; then
-            sed_in_place "/^dep-upp: /c dep-upp: $PACKAGE_DEP_UPP" "$PACKAGE_RECEIPT_FILEPATH"
+            sed -i "/^dep-upp: /c dep-upp: $PACKAGE_DEP_UPP" "$PACKAGE_RECEIPT_FILEPATH"
         else
-            sed_in_place "/^bsystem: /i dep-upp: $PACKAGE_DEP_UPP" "$PACKAGE_RECEIPT_FILEPATH"
+            sed -i "/^bsystem: /i dep-upp: $PACKAGE_DEP_UPP" "$PACKAGE_RECEIPT_FILEPATH"
         fi
     }
 
     cat >> "$PACKAGE_RECEIPT_FILEPATH" <<EOF
-builtfor: $TARGET_PLATFORM_SPEC
 builtby: xcpkg-$XCPKG_VERSION
 builtat: $TIMESTAMP_UNIX
 buildon:
@@ -1330,23 +1343,24 @@ buildon:
     os-ncpu: $NATIVE_OS_NCPU
     os-euid: $NATIVE_OS_EUID
     os-egid: $NATIVE_OS_EGID
+builtfor: $TARGET_PLATFORM_SPEC
 EOF
 }
+
 
 # __load_receipt_of_the_given_package <PACKAGE-NAME|PACKAGE-SPEC>
   __load_receipt_of_the_given_package() {
     PACKAGE_SPEC=
     PACKAGE_SPEC="$(inspect_package_spec "$1")"
 
-    is_package_installed "$PACKAGE_SPEC"
+    is_package_installed "$PACKAGE_SPEC" || return $?
 
-    [ $? -eq 0 ] || return $?
-
-    PACKAGE_INSTALLED_DIR="$XCPKG_PACKAGE_INSTALLED_ROOT/$PACKAGE_SPEC"
+    PACKAGE_INSTALLED_DIR="$(readlink -f "$XCPKG_PACKAGE_INSTALLED_ROOT/$PACKAGE_SPEC")"
 
     PACKAGE_RECEIPT_FILEPATH="$PACKAGE_INSTALLED_DIR/.xcpkg/RECEIPT.yml"
 
     unset RECEIPT_PACKAGE_PKGNAME
+    unset RECEIPT_PACKAGE_PKGTYPE
     unset RECEIPT_PACKAGE_SUMMARY
     unset RECEIPT_PACKAGE_VERSION
     unset RECEIPT_PACKAGE_LICENSE
@@ -1365,10 +1379,14 @@ EOF
     unset RECEIPT_PACKAGE_FIX_URL
     unset RECEIPT_PACKAGE_FIX_URI
     unset RECEIPT_PACKAGE_FIX_SHA
+    unset RECEIPT_PACKAGE_FIX_OPT
 
     unset RECEIPT_PACKAGE_RES_URL
     unset RECEIPT_PACKAGE_RES_URI
     unset RECEIPT_PACKAGE_RES_SHA
+
+    unset RECEIPT_PACKAGE_PATCHES
+    unset RECEIPT_PACKAGE_RESLIST
 
     unset RECEIPT_PACKAGE_DEP_PKG
     unset RECEIPT_PACKAGE_DEP_UPP
@@ -1377,11 +1395,18 @@ EOF
 
     unset RECEIPT_PACKAGE_BSYSTEM
     unset RECEIPT_PACKAGE_BSCRIPT
-    unset RECEIPT_PACKAGE_DOPATCH
-    unset RECEIPT_PACKAGE_INSTALL
-    unset RECEIPT_PACKAGE_SYMLINK
 
-    unset RECEIPT_PACKAGE_PARALLEL
+    unset RECEIPT_PACKAGE_ONSTART
+    unset RECEIPT_PACKAGE_ONREADY
+    unset RECEIPT_PACKAGE_ONFINAL
+
+    unset RECEIPT_PACKAGE_DO12345
+    unset RECEIPT_PACKAGE_DOPATCH
+    unset RECEIPT_PACKAGE_PREPARE
+    unset RECEIPT_PACKAGE_DOBUILD
+    unset RECEIPT_PACKAGE_DOTWEAK
+
+    unset RECEIPT_PACKAGE_CAVEATS
 
     unset RECEIPT_PACKAGE_BUILTBY
     unset RECEIPT_PACKAGE_BUILTAT
@@ -1392,8 +1417,13 @@ EOF
     unset RECEIPT_PACKAGE_BUILTFOR_PLATFORM_VERS
     unset RECEIPT_PACKAGE_BUILTFOR_PLATFORM_ARCH
 
+    unset RECEIPT_PACKAGE_PARALLEL
+    unset RECEIPT_PACKAGE_DEVELOPER
+
+    #########################################################################################
 
     RECEIPT_PACKAGE_PKGNAME="$(yq '.pkgname | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
+    RECEIPT_PACKAGE_PKGTYPE="$(yq '.pkgtype | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
     RECEIPT_PACKAGE_SUMMARY="$(yq '.summary | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
     RECEIPT_PACKAGE_LICENSE="$(yq '.license | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
     RECEIPT_PACKAGE_VERSION="$(yq '.version | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
@@ -1412,10 +1442,13 @@ EOF
     RECEIPT_PACKAGE_FIX_URL="$(yq '.fix-url | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
     RECEIPT_PACKAGE_FIX_URI="$(yq '.fix-uri | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
     RECEIPT_PACKAGE_FIX_SHA="$(yq '.fix-sha | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
+    RECEIPT_PACKAGE_FIX_OPT="$(yq '.fix-opt | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
 
     RECEIPT_PACKAGE_RES_URL="$(yq '.res-url | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
     RECEIPT_PACKAGE_RES_URI="$(yq '.res-uri | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
     RECEIPT_PACKAGE_RES_SHA="$(yq '.res-sha | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
+    RECEIPT_PACKAGE_RESLIST="$(yq '.reslist | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
+    RECEIPT_PACKAGE_PATCHES="$(yq '.patches | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
 
     RECEIPT_PACKAGE_DEP_PKG="$(yq '.dep-pkg | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
     RECEIPT_PACKAGE_DEP_UPP="$(yq '.dep-upp | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
@@ -1431,10 +1464,17 @@ EOF
     RECEIPT_PACKAGE_PPFLAGS="$(yq '.ppflags | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
     RECEIPT_PACKAGE_LDFLAGS="$(yq '.ldflags | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
 
-    RECEIPT_PACKAGE_DOPATCH="$(yq '.dopatch | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
-    RECEIPT_PACKAGE_INSTALL="$(yq '.install | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
+    RECEIPT_PACKAGE_ONSTART="$(yq '.onstart | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
+    RECEIPT_PACKAGE_ONREADY="$(yq '.onready | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
+    RECEIPT_PACKAGE_ONFINAL="$(yq '.onfinal | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
 
-    RECEIPT_PACKAGE_SYMLINK="$(yq '.symlink | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
+    RECEIPT_PACKAGE_DO12345="$(yq '.do12345 | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
+    RECEIPT_PACKAGE_DOPATCH="$(yq '.dopatch | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
+    RECEIPT_PACKAGE_PREPARE="$(yq '.prepare | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
+    RECEIPT_PACKAGE_DOBUILD="$(yq '.install | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
+    RECEIPT_PACKAGE_DOTWEAK="$(yq '.dotweak | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
+
+    RECEIPT_PACKAGE_CAVEATS="$(yq '.caveats | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
 
     RECEIPT_PACKAGE_BUILTBY="$(yq '.builtby | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
     RECEIPT_PACKAGE_BUILTAT="$(yq '.builtat | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
@@ -1445,8 +1485,20 @@ EOF
 
     RECEIPT_PACKAGE_DEVELOPER="$(yq '.developer | select(. != null)' "$PACKAGE_RECEIPT_FILEPATH")"
 
-    if [ "${PACKAGE_SPEC##*/}" != "$RECEIPT_PACKAGE_PKGNAME" ] ; then
-        error "$PACKAGE_RECEIPT_FILEPATH is broken. value of RECEIPT_PACKAGE_PKGNAME does not identical with your request: ${PACKAGE_SPEC##*/}"
+    #########################################################################################
+
+    [ -z "$RECEIPT_PACKAGE_PKGNAME" ] && abort 1 "receipt scheme error. pkgname mapping was not found in $PACKAGE_RECEIPT_FILEPATH."
+    [ -z "$RECEIPT_PACKAGE_PKGTYPE" ] && abort 1 "receipt scheme error. pkgtype mapping was not found in $PACKAGE_RECEIPT_FILEPATH."
+    [ -z "$RECEIPT_PACKAGE_VERSION" ] && abort 1 "receipt scheme error. version mapping was not found in $PACKAGE_RECEIPT_FILEPATH."
+    [ -z "$RECEIPT_PACKAGE_SUMMARY" ] && abort 1 "receipt scheme error. summary mapping was not found in $PACKAGE_RECEIPT_FILEPATH."
+    [ -z "$RECEIPT_PACKAGE_WEB_URL" ] && abort 1 "receipt scheme error. web-url mapping was not found in $PACKAGE_RECEIPT_FILEPATH."
+    [ -z "$RECEIPT_PACKAGE_BUILTBY" ] && abort 1 "receipt scheme error. builtby mapping was not found in $PACKAGE_RECEIPT_FILEPATH."
+    [ -z "$RECEIPT_PACKAGE_BUILTAT" ] && abort 1 "receipt scheme error. builtat mapping was not found in $PACKAGE_RECEIPT_FILEPATH."
+
+    [ "${#RECEIPT_PACKAGE_BUILTAT}" -eq 10 ] || abort 1 "receipt scheme error. builtat mapping's value length must be 10."
+
+    if [ "${PACKAGE_SPEC#*/}" != "$RECEIPT_PACKAGE_PKGNAME" ] ; then
+        error "$PACKAGE_RECEIPT_FILEPATH is broken. value of RECEIPT_PACKAGE_PKGNAME does not identical with your request: ${PACKAGE_SPEC#*/}"
         return 1
     fi
 
@@ -1455,19 +1507,13 @@ EOF
         return 1
     fi
 
+    #########################################################################################
+
     RECEIPT_PACKAGE_BUILTFOR_PLATFORM="$RECEIPT_PACKAGE_BUILTFOR"
 
-    RECEIPT_PACKAGE_BUILTFOR_PLATFORM_NAME="$(printf '%s' "$RECEIPT_PACKAGE_BUILTFOR_PLATFORM" | cut -d- -f1)"
-    RECEIPT_PACKAGE_BUILTFOR_PLATFORM_VERS="$(printf '%s' "$RECEIPT_PACKAGE_BUILTFOR_PLATFORM" | cut -d- -f2)"
-    RECEIPT_PACKAGE_BUILTFOR_PLATFORM_ARCH="$(printf '%s' "$RECEIPT_PACKAGE_BUILTFOR_PLATFORM" | cut -d- -f3)"
-
-    [ -z "$RECEIPT_PACKAGE_BUILTBY" ] && abort 1 "receipt scheme error. builtby mapping was not found in $PACKAGE_RECEIPT_FILEPATH."
-    [ -z "$RECEIPT_PACKAGE_BUILTAT" ] && abort 1 "receipt scheme error. builtat mapping was not found in $PACKAGE_RECEIPT_FILEPATH."
-    [ -z "$RECEIPT_PACKAGE_VERSION" ] && abort 1 "receipt scheme error. version mapping was not found in $PACKAGE_RECEIPT_FILEPATH."
-    [ -z "$RECEIPT_PACKAGE_SUMMARY" ] && abort 1 "receipt scheme error. summary mapping was not found in $PACKAGE_RECEIPT_FILEPATH."
-    [ -z "$RECEIPT_PACKAGE_WEB_URL" ] && abort 1 "receipt scheme error. web-url mapping was not found in $PACKAGE_RECEIPT_FILEPATH."
-
-    [ "${#RECEIPT_PACKAGE_BUILTAT}" -eq 10 ] || abort 1 "receipt scheme error. timestamp mapping's value length must be 10."
+    RECEIPT_PACKAGE_BUILTFOR_PLATFORM_NAME="$(printf '%s\n' "$RECEIPT_PACKAGE_BUILTFOR" | cut -d- -f1)"
+    RECEIPT_PACKAGE_BUILTFOR_PLATFORM_VERS="$(printf '%s\n' "$RECEIPT_PACKAGE_BUILTFOR" | cut -d- -f2)"
+    RECEIPT_PACKAGE_BUILTFOR_PLATFORM_ARCH="$(printf '%s\n' "$RECEIPT_PACKAGE_BUILTFOR" | cut -d- -f3)"
 }
 
 # }}}
@@ -1675,12 +1721,15 @@ __search_packages() {
         --arg dep_upp "$PACKAGE_DEP_UPP" \
         --arg dep_pym "$PACKAGE_DEP_PYM" \
         --arg dep_plm "$PACKAGE_DEP_PLM" \
+        --arg onstart "$PACKAGE_ONSTART" \
         --arg onready "$PACKAGE_ONREADY" \
+        --arg onfinal "$PACKAGE_ONFINAL" \
         --arg do12345 "$PACKAGE_DO12345" \
         --arg dopatch "$PACKAGE_DOPATCH" \
         --arg prepare "$PACKAGE_PREPARE" \
         --arg install "$PACKAGE_DOBUILD" \
         --arg dotweak "$PACKAGE_DOTWEAK" \
+        --arg caveats "$PACKAGE_CAVEATS" \
         --arg bsystem "$PACKAGE_BSYSTEM" \
         --arg binbstd "$PACKAGE_BINBSTD" \
         --arg ccflags "$PACKAGE_CCFLAGS" \
@@ -1720,12 +1769,15 @@ __search_packages() {
     "ppflags":$ppflags,
     "ldflags":$ldflags,
     "parallel":$parallel,
+    "onstart":$onstart,
     "onready":$onready,
+    "onfinal":$onfinal,
     "do12345":$do12345,
     "dopatch":$dopatch,
     "prepare":$prepare,
     "install":$install,
-    "dotweak":$dotweak
+    "dotweak":$dotweak,
+    "caveats":$caveats
 }' | jq 'with_entries(select(.value != ""))'
 }
 
@@ -1859,9 +1911,17 @@ EOF
         --json)
             __info_the_given_available_package_as_json "$1"
             ;;
+        onstart)
+            __load_formula_of_the_given_package "$1"
+            printf '%s\n' "$PACKAGE_ONSTART"
+            ;;
         onready)
             __load_formula_of_the_given_package "$1"
             printf '%s\n' "$PACKAGE_ONREADY"
+            ;;
+        onfinal)
+            __load_formula_of_the_given_package "$1"
+            printf '%s\n' "$PACKAGE_ONFINAL"
             ;;
         do12345)
             __load_formula_of_the_given_package "$1"
@@ -1882,6 +1942,10 @@ EOF
         dotweak)
             __load_formula_of_the_given_package "$1"
             printf '%s\n' "$PACKAGE_DOTWEAK"
+            ;;
+        caveats)
+            __load_formula_of_the_given_package "$1"
+            printf '%s\n' "$PACKAGE_CAVEATS"
             ;;
         developer)
             __load_formula_of_the_given_package "$1"
@@ -3139,7 +3203,7 @@ __install_the_given_package_onexit() {
 
 # Note: this function must run in a subshell
 __install_the_given_package() {
-    printf '%b\n' "${COLOR_PURPLE}=============== Installing ${COLOR_OFF}${COLOR_GREEN}${1}${COLOR_OFF}${COLOR_PURPLE} ===============${COLOR_OFF}"
+    printf '%b\n' "${COLOR_PURPLE}>>> Installation ${COLOR_OFF}${COLOR_GREEN}${1}${COLOR_OFF}${COLOR_PURPLE} start${COLOR_OFF}"
 
     unset PACKAGE_WORKING_DIR
 
@@ -3228,6 +3292,20 @@ PACKAGE_WORKING_DIR = $PACKAGE_WORKING_DIR
 PACKAGE_BCACHED_DIR = $PACKAGE_BCACHED_DIR
 PACKAGE_INSTALL_DIR = $PACKAGE_INSTALL_DIR
 EOF
+
+    #########################################################################################
+
+    step "onstart"
+
+    if [ -z "$PACKAGE_ONSTART" ] ; then
+        note "onstart mapping was not found in formula, skipped."
+    else
+        eval "
+onstart() {
+$PACKAGE_ONSTART
+}"
+        onstart
+    fi
 
     #########################################################################################
 
@@ -5242,6 +5320,32 @@ $PACKAGE_DOTWEAK
 
     step "show installed files in tree-like format"
     run tree --dirsfirst -a "$PACKAGE_INSTALL_DIR"
+
+    #########################################################################################
+
+    step "onfinal"
+
+    if [ -z "$PACKAGE_ONFINAL" ] ; then
+        note "onfinal mapping was not found in formula, skipped."
+    else
+        if [ "$PWD" != "$PACKAGE_INSTALL_DIR" ] ; then
+            run     cd "$PACKAGE_INSTALL_DIR"
+        fi
+
+        eval "
+onfinal() {
+$PACKAGE_ONFINAL
+}"
+        onfinal
+    fi
+
+    #########################################################################################
+
+    printf '\n%b\n' "${COLOR_PURPLE}<<< Installation ${COLOR_OFF}${COLOR_GREEN}${1}${COLOR_OFF}${COLOR_PURPLE} end${COLOR_OFF}"
+
+    if [ -n "$PACKAGE_CAVEATS" ] ; then
+        printf '\n%b\n' "${COLOR_YELLOW}🔥  Caveats:\n\n$PACKAGE_CAVEATS${COLOR_OFF}" >&2
+    fi
 }
 
 __tweak_mach_o_files() {
@@ -7727,7 +7831,7 @@ XCPKG_PATH="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"
 
 XCPKG_ACTION="$*"
 
-XCPKG_VERSION=0.18.0
+XCPKG_VERSION=0.18.1
 
 XCPKG_OFFICIAL_FORMULA_REPO_URL='https://github.com/leleliu008/xcpkg-formula-repository-official-core'
 
