optimized
Signed-off-by: leleliu008 <leleliu008@gmail.com>

diff --git a/xcpkg b/xcpkg
--- a/xcpkg
+++ b/xcpkg
@@ -3545,7 +3545,7 @@ __install_the_given_packages() {
 
     case $BUILD_SYSTEM_NAME in
         cmake)
-            CMAKE="$HOME/.uppm/installed/cmake/bin/cmake"
+            CMAKE="$(command -v cmake)" || abort 1 "command not found: cmake"
 
             run "$CMAKE" -S . -B build.d -DCMAKE_INSTALL_PREFIX=$XCPKG_CORE_DIR -DCMAKE_INSTALL_LIBDIR=lib -DBUILD_SHARED_LIBS=ON "$BUILD_CONFIG_ARGS"
             run "$CMAKE" --build   build.d -- -j$BUILD_NJOBS
@@ -3565,7 +3565,7 @@ __install_the_given_packages() {
                 *)  run ./configure "--prefix=$XCPKG_CORE_DIR" "$BUILD_CONFIG_ARGS"
             esac
 
-            GMAKE="$HOME/.uppm/installed/gmake/bin/gmake"
+            GMAKE="$(command -v gmake)" || abort 1 "command not found: gmake"
 
             run "$GMAKE" "--jobs=$NATIVE_OS_NCPU"
             run "$GMAKE" install
@@ -4089,8 +4089,6 @@ $DOT_CONTENT
     #########################################################################################
 
     step "install needed packages via uppm"
-
-    UPPM="$XCPKG_CORE_BIN_DIR/uppm"
 
     run "$UPPM" env
     run "$UPPM" update
@@ -6934,8 +6932,6 @@ __setup_uppm() {
 
     export SSL_CERT_FILE="$XCPKG_CORE_DIR/etc/ssl/certs/cacert.pem"
 
-    UPPM="$XCPKG_CORE_BIN_DIR/uppm"
-
     run "$UPPM" env
     run "$UPPM" update
 
@@ -7224,6 +7220,8 @@ main() {
     XCPKG_CORE_DIR="$XCPKG_HOME/core"
     XCPKG_CORE_BIN_DIR="$XCPKG_CORE_DIR/bin"
 
+    UPPM="$XCPKG_CORE_BIN_DIR/uppm"
+
     # DO NOT use this environment variable
     # https://cmake.org/cmake/help/latest/envvar/MACOSX_DEPLOYMENT_TARGET.html
     unset   MACOSX_DEPLOYMENT_TARGET
@@ -7246,9 +7244,10 @@ xcpkg.version : $XCPKG_VERSION
 xcpkg.homedir : $XCPKG_HOME
 xcpkg.exepath : $XCPKG
 xcpkg.website : https://github.com/leleliu008/xcpkg
+
 EOF
-            if [ -f "$XCPKG_CORE_DIR/env" ] && [ -f "$XCPKG_CORE_DIR/bin/uppm" ] ; then
-                "$XCPKG_CORE_DIR/bin/uppm" env
+            if [ -f "$XCPKG_CORE_DIR/env" ] && [ -f "$UPPM" ] ; then
+                "$UPPM" env
             fi
             return 0
             ;;
