optimized
Signed-off-by: leleliu008 <leleliu008@gmail.com>

diff --git a/xcpkg b/xcpkg
--- a/xcpkg
+++ b/xcpkg
@@ -127,38 +127,16 @@ bppend_to_ACLOCAL_PATH() {
 }
 
 sed_in_place() {
-    if command -v gsed > /dev/null ; then
-        unset SED_IN_PLACE_ACTION
-        SED_IN_PLACE_ACTION="$1"
-        shift
-        # contains ' but not contains \'
-        if printf "$SED_IN_PLACE_ACTION" | hexdump -v -e '1/1 "%02X" " "' | grep -q 27 && ! printf "$SED_IN_PLACE_ACTION" | hexdump -v -e '1/1 "%02X" ""' | grep -q '5C 27' ; then
-            run gsed -i "\"$SED_IN_PLACE_ACTION\"" "$@"
-        else
-            run gsed -i "'$SED_IN_PLACE_ACTION'" "$@"
-        fi
-    elif command -v sed  > /dev/null ; then
-        if sed -i 's/a/b/g' $(mktemp) 2> /dev/null ; then
-            unset SED_IN_PLACE_ACTION
-            SED_IN_PLACE_ACTION="$1"
-            shift
-            if printf "$SED_IN_PLACE_ACTION" | hexdump -v -e '1/1 "%02X" " "' | grep -q 27 && ! printf "$SED_IN_PLACE_ACTION" | hexdump -v -e '1/1 "%02X" ""' | grep -q '5C 27' ; then
-                run sed -i "\"$SED_IN_PLACE_ACTION\"" "$@"
-            else
-                run sed -i "'$SED_IN_PLACE_ACTION'" "$@"
-            fi
-        else
-            unset SED_IN_PLACE_ACTION
-            SED_IN_PLACE_ACTION="$1"
-            shift
-            if printf "$SED_IN_PLACE_ACTION" | hexdump -v -e '1/1 "%02X" " "' | grep -q 27 && ! printf "$SED_IN_PLACE_ACTION" | hexdump -v -e '1/1 "%02X" ""' | grep -q '5C 27' ; then
-                run sed -i '""' "\"$SED_IN_PLACE_ACTION\"" "$@"
-            else
-                run sed -i '""' "'$SED_IN_PLACE_ACTION'" "$@"
-            fi
-        fi
+    if [ "$RUN_SILENT" = 1 ] ; then
+        gsed -i "$@"
     else
-        abort 1 "please install sed utility."
+        if [ -z "$SED" ] ; then
+            SED="$(command -v gsed || command -v sed)" || abort 1 "command not found: gsed"
+        fi
+
+        export SED
+
+        "$XCPKG_CORE_DIR/libexec/sed-in-place" "$@"
     fi
 }
 
@@ -3590,25 +3568,25 @@ __install_the_given_packages() {
             NATIVE_PACKAGE_BUILD_CONFIG_ARGS='-DINSTALL_EXECUTABLES=OFF -DINSTALL_LIBRARIES=ON -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF'
             ;;
         perl)
-            NATIVE_PACKAGE_SRC_URL='https://cpan.metacpan.org/authors/id/R/RJ/RJBS/perl-5.36.0.tar.xz'
-            NATIVE_PACKAGE_SRC_SHA='0f386dccbee8e26286404b2cca144e1005be65477979beb9b1ba272d4819bcf0'
+            NATIVE_PACKAGE_SRC_URL='https://cpan.metacpan.org/authors/id/R/RJ/RJBS/perl-5.38.0.tar.xz'
+            NATIVE_PACKAGE_SRC_SHA='eca551caec3bc549a4e590c0015003790bdd1a604ffe19cc78ee631d51f7072e'
             NATIVE_PACKAGE_DEPENDENCIES=
             NATIVE_PACKAGE_BUILD_SYSTEM_NAME='configure'
             NATIVE_PACKAGE_BUILD_CONFIG_ARGS=
             ;;
         openssl)
-            NATIVE_PACKAGE_SRC_URL='https://www.openssl.org/source/openssl-3.0.5.tar.gz'
-            NATIVE_PACKAGE_SRC_SHA='aa7d8d9bef71ad6525c55ba11e5f4397889ce49c2c9349dcea6d3e4f0b024a7a'
+            NATIVE_PACKAGE_SRC_URL='https://www.openssl.org/source/openssl-3.1.1.tar.gz'
+            NATIVE_PACKAGE_SRC_SHA='b3aa61334233b852b63ddb048df181177c2c659eb9d4376008118f9c08d07674'
             NATIVE_PACKAGE_DEPENDENCIES='perl'
             NATIVE_PACKAGE_BUILD_SYSTEM_NAME='configure'
             NATIVE_PACKAGE_BUILD_CONFIG_ARGS=
             ;;
         texinfo)
-            NATIVE_PACKAGE_SRC_URL='https://ftp.gnu.org/gnu/texinfo/texinfo-7.0.tar.xz'
-            NATIVE_PACKAGE_SRC_SHA='20744b82531ce7a04d8cee34b07143ad59777612c3695d5855f29fba40fbe3e0'
+            NATIVE_PACKAGE_SRC_URL='https://ftp.gnu.org/gnu/texinfo/texinfo-7.1.tar.xz'
+            NATIVE_PACKAGE_SRC_SHA='deeec9f19f159e046fdf8ad22231981806dac332cc372f1c763504ad82b30953'
             NATIVE_PACKAGE_DEPENDENCIES='perl'
             NATIVE_PACKAGE_BUILD_SYSTEM_NAME='configure'
-            NATIVE_PACKAGE_BUILD_CONFIG_ARGS='--with-included-regex --enable-threads=posix'
+            NATIVE_PACKAGE_BUILD_CONFIG_ARGS='--with-included-regex --enable-threads=posix --disable-nls'
             ;;
         help2man)
             NATIVE_PACKAGE_SRC_URL='https://ftp.gnu.org/gnu/help2man/help2man-1.49.3.tar.xz'
@@ -3660,8 +3638,8 @@ __install_the_given_packages() {
             NATIVE_PACKAGE_BUILD_CONFIG_ARGS='--disable-dependency-tracking --enable-static --disable-shared --disable-nls --enable-largefile --enable-libgdbm-compat --without-readline'
             ;;
         sqlite3)
-            NATIVE_PACKAGE_SRC_URL='https://www.sqlite.org/2023/sqlite-autoconf-3410100.tar.gz'
-            NATIVE_PACKAGE_SRC_SHA='4dadfbeab9f8e16c695d4fbbc51c16b2f77fb97ff4c1c3d139919dfc038c9e33'
+            NATIVE_PACKAGE_SRC_URL='https://www.sqlite.org/2023/sqlite-autoconf-3440000.tar.gz'
+            NATIVE_PACKAGE_SRC_SHA='b9cd386e7cd22af6e0d2a0f06d0404951e1bef109e42ea06cc0450e10cd15550'
             NATIVE_PACKAGE_DEPENDENCIES='zlib'
             NATIVE_PACKAGE_BUILD_SYSTEM_NAME='configure'
             NATIVE_PACKAGE_BUILD_CONFIG_ARGS='--disable-dependency-tracking --enable-static --disable-shared --enable-largefile --disable-editline --disable-readline'
@@ -3688,8 +3666,8 @@ __install_the_given_packages() {
             NATIVE_PACKAGE_BUILD_CONFIG_ARGS='--disable-dependency-tracking --enable-static --enable-shared --disable-docs'
             ;;
         python3)
-            NATIVE_PACKAGE_SRC_URL='https://www.python.org/ftp/python/3.11.2/Python-3.11.2.tgz'
-            NATIVE_PACKAGE_SRC_SHA='2411c74bda5bbcfcddaf4531f66d1adc73f247f529aee981b029513aefdbf849'
+            NATIVE_PACKAGE_SRC_URL='https://www.python.org/ftp/python/3.11.6/Python-3.11.6.tgz'
+            NATIVE_PACKAGE_SRC_SHA='c049bf317e877cbf9fce8c3af902436774ecef5249a29d10984ca3a37f7f4736'
             NATIVE_PACKAGE_DEPENDENCIES='zlib libbz2 liblzma gdbm expat sqlite3 libffi openssl perl'
             NATIVE_PACKAGE_BUILD_SYSTEM_NAME='configure'
             NATIVE_PACKAGE_BUILD_CONFIG_ARGS="--with-system-expat --with-system-ffi --with-openssl=$NATIVE_PACKAGE_INSTALLED_ROOT/openssl --with-ensurepip=yes --with-lto --enable-ipv6 --enable-shared --enable-largefile --disable-option-checking --disable-nls --disable-debug --disable-loadable-sqlite-extensions --disable-profiling"
@@ -3700,6 +3678,20 @@ __install_the_given_packages() {
             NATIVE_PACKAGE_DEPENDENCIES='perl expat'
             NATIVE_PACKAGE_BUILD_SYSTEM_NAME='configure'
             NATIVE_PACKAGE_BUILD_CONFIG_ARGS=
+            ;;
+        libpcre2)
+            NATIVE_PACKAGE_SRC_URL='https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.42/pcre2-10.42.tar.bz2'
+            NATIVE_PACKAGE_SRC_SHA='8d36cd8cb6ea2a4c2bb358ff6411b0c788633a2a45dabbf1aeb4b701d1b5e840'
+            NATIVE_PACKAGE_DEPENDENCIES=
+            NATIVE_PACKAGE_BUILD_SYSTEM_NAME='cmake'
+            NATIVE_PACKAGE_BUILD_CONFIG_ARGS='-DCMAKE_C_STANDARD=99 -DCMAKE_C_STANDARD_REQUIRED=ON -DPCRE2_BUILD_PCRE2_8=ON -DPCRE2_BUILD_PCRE2_16=ON -DPCRE2_BUILD_PCRE2_32=ON -DPCRE2_BUILD_PCRE2GREP=OFF -DPCRE2_BUILD_TESTS=OFF -DPCRE2_DEBUG=OFF -DPCRE2_SUPPORT_VALGRIND=OFF -DPCRE2_SUPPORT_UNICODE=ON'
+            ;;
+        swig)
+            NATIVE_PACKAGE_SRC_URL='https://downloads.sourceforge.net/project/swig/swig/swig-4.1.1/swig-4.1.1.tar.gz'
+            NATIVE_PACKAGE_SRC_SHA='2af08aced8fcd65cdb5cc62426768914bedc735b1c250325203716f78e39ac9b'
+            NATIVE_PACKAGE_DEPENDENCIES='libpcre2'
+            NATIVE_PACKAGE_BUILD_SYSTEM_NAME='configure'
+            NATIVE_PACKAGE_BUILD_CONFIG_ARGS='--enable-ccache --enable-cpp11-testing --with-popen --with-pcre --without-boost --without-android --without-java --without-javascript --without-python --without-perl5 --without-ruby --without-php --without-tcl --without-guile --without-octave --without-scilab --without-ocaml --without-mzscheme --without-csharp --without-lua --without-r --without-d --without-go'
             ;;
         *)  abort 1 "unknown native package name: $1"
     esac
@@ -4340,6 +4332,7 @@ $DOT_CONTENT
             intltool) PACKAGE_DEP_UPP_T1="$PACKAGE_DEP_UPP_T1 gmake cmake" ; PACKAGE_DEP_UPP_T2="$PACKAGE_DEP_UPP_T2 $item" ;;
             python3)  PACKAGE_DEP_UPP_T1="$PACKAGE_DEP_UPP_T1 gmake cmake" ; PACKAGE_DEP_UPP_T2="$PACKAGE_DEP_UPP_T2 $item" ;;
             ruby)     PACKAGE_DEP_UPP_T1="$PACKAGE_DEP_UPP_T1 gmake cmake" ; PACKAGE_DEP_UPP_T2="$PACKAGE_DEP_UPP_T2 $item" ;;
+            swig)     PACKAGE_DEP_UPP_T1="$PACKAGE_DEP_UPP_T1 gmake cmake" ; PACKAGE_DEP_UPP_T2="$PACKAGE_DEP_UPP_T2 $item" ;;
             libtool)  PACKAGE_DEP_UPP_T1="$PACKAGE_DEP_UPP_T1 gmake gm4"   ; PACKAGE_DEP_UPP_T2="$PACKAGE_DEP_UPP_T2 $item" ;;
             autoconf) PACKAGE_DEP_UPP_T1="$PACKAGE_DEP_UPP_T1 gmake gm4"   ; PACKAGE_DEP_UPP_T2="$PACKAGE_DEP_UPP_T2 $item" ;;
             automake) PACKAGE_DEP_UPP_T1="$PACKAGE_DEP_UPP_T1 gmake gm4"   ; PACKAGE_DEP_UPP_T2="$PACKAGE_DEP_UPP_T2 $item" ;;
@@ -7315,6 +7308,47 @@ EOF
     run cc -std=c99 -o libexec/wrapper-target-c++  wrapper-target-c++.c
     run cc -std=c99 -o libexec/wrapper-target-objc wrapper-target-objc.c
 
+    ##################################################################################
+
+    cat > sed-in-place.c <<EOF
+#include <stdio.h>
+#include <stdlib.h>
+#include <unistd.h>
+
+int main(int argc, char* argv[]) {
+    char * const sed = getenv("SED");
+
+    if (sed == NULL || sed[0] == '\0') {
+        fprintf(stderr, "SED environment variable was not set.\n");
+        return 1;
+    }
+
+    /////////////////////////////////////////////////////////////////
+
+    char* argv2[argc + 2];
+
+    argv2[0] = sed;
+    argv2[1] = (char*)"-i";
+
+    for (int i = 1; i < argc; i++) {
+        argv2[i + 1] = argv[i];
+    }
+
+    argv2[argc + 1] = NULL;
+
+    for (int i = 0; argv2[i] != NULL; i++) {
+        fprintf(stderr, "%s ", argv2[i]);
+    }
+    fprintf(stderr, "\n");
+
+    execv (sed, argv2);
+    perror(sed);
+    return 255;
+}
+EOF
+
+    run cc -std=c99 -o libexec/sed-in-place sed-in-place.c
+
     #################################################################################
 
     if [ -d        "$XCPKG_CORE_DIR" ] ; then
@@ -7579,7 +7613,7 @@ main() {
 
     XCPKG="$CURRENT_SCRIPT_FILEPATH"
 
-    XCPKG_VERSION=0.13.13
+    XCPKG_VERSION=0.13.14
 
     XCPKG_OFFICAL_FORMULA_REPO_URL='https://github.com/leleliu008/xcpkg-formula-repository-offical-core'
 
